<a href="https://colab.research.google.com/github/js-valencia/Algebra/blob/main/AlgebraMatrices_mult_m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[1, 0],
              [6, -2],
              [-1, 4],])

B = np.array([[2, -5, 1, -2],
              [3, 2, 0, -1],
              ])
print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor = A[1,0] * B[0,0] + A[1,1] * B[1,0]
print("El valor de C[1,0] es: ", valor)


Matriz A:
 [[ 1  0]
 [ 6 -2]
 [-1  4]]

Matriz B:
 [[ 2 -5  1 -2]
 [ 3  2  0 -1]]

 Producto matricial (A * B):
 [[  2  -5   1  -2]
 [  6 -34   6 -10]
 [ 10  13  -1  -2]]
El valor de C[1,0] es:  6
