<a href="https://colab.research.google.com/github/js-valencia/Algebra/blob/main/AlgebraMatrices_mult_m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from datetime import datetime
import pytz

# Definir la zona horaria de Ecuador
ecuador_tz = pytz.timezone("America/Guayaquil")

# Obtener la hora actual en Ecuador
hora_actual = datetime.now(ecuador_tz)

# Imprimir la hora en formato legible
print("Fecha: ", hora_actual.strftime("%Y-%m-%d"))
print("Mis nombres son: José David Valencia Condoy")
print("Mi carrera es: Computación")

# Definir dos matrices A y B de 3x3
A = np.array([[1, 0],
              [6, -2],
              [-1, 4],])

B = np.array([[2, -5, 1, -2],
              [3, 2, 0, -1],
              ])
print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor = A[1,0] * B[0,0] + A[1,1] * B[1,0]
print("El valor de C[1,0] es: ", valor)


Fecha:  2025-10-20
Mis nombres son: José David Valencia Condoy
Mi carrera es: Computación
Matriz A:
 [[ 1  0]
 [ 6 -2]
 [-1  4]]

Matriz B:
 [[ 2 -5  1 -2]
 [ 3  2  0 -1]]

 Producto matricial (A * B):
 [[  2  -5   1  -2]
 [  6 -34   6 -10]
 [ 10  13  -1  -2]]
El valor de C[1,0] es:  6
